# Generated by Django 5.0.6 on 2024-06-18 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupu', '0002_aktas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktas',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lupu.vatinvoice'),
            preserve_default=False,
        ),
    ]
