# Generated by Django 5.0.6 on 2024-06-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupu', '0003_aktas_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatinvoice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aktas',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lupu.vatinvoice'),
        ),
        migrations.AlterField(
            model_name='aktas',
            name='item_name',
            field=models.CharField(default='Default Item', max_length=255),
        ),
        migrations.AlterField(
            model_name='aktas',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aktas',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aktas',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aktas',
            name='unit',
            field=models.CharField(default='vnt', max_length=50),
        ),
        migrations.AlterField(
            model_name='aktas',
            name='usage',
            field=models.CharField(default='Default Usage', max_length=255),
        ),
        migrations.AlterField(
            model_name='vatinvoice',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vatinvoice',
            name='invoice_number',
            field=models.CharField(max_length=255),
        ),
    ]
