# Generated by Django 5.0.6 on 2024-06-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupu', '0004_vatinvoice_price_alter_aktas_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vatinvoice',
            name='amount',
        ),
    ]
